package common

const (
	// EthereumMainnet ...
	EthereumMainnet string = "Ethereum Mainnet"
	// EthereumRopsten ...
	EthereumRopsten string = "Ethereum Testnet - Ropsten"
	// EthereumKovan ...
	EthereumKovan string = "Ethereum Testnet - Kovan"
	// BSCMainnet ...
	BSCMainnet string = "Binance Smart Chain Mainnet"
	// BSCTestnet ...
	BSCTestnet string = "Binance Smart Chain Testnet"
	// UnknowNetwork ...
	UnknowNetwork string = "Unknow Network"
)
